language: java

jdk: oraclejdk8

addons:
  postgresql: "9.3"

before_script:
  - psql -f 'db/postgresql.sql' -U postgres
  - cp src/main/resources/ga/rugal/core/db_travis.clj  src/main/resources/ga/rugal/core/db.clj
